import '@/styles/global.css'
import type { Metadata } from 'next'

interface RootLayoutProps {
  readonly children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'NextJS Starter',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="es-MX">
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
